name: Pull requests

on:
  pull_request:
    branches:
      - "**"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
