name: Push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install modules
        run: yarn install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
      - name: Remove this
        run: |
          git config --global user.email "ci@journify.io"
          git config --global user.name "Journify CI bot"
          npm run patch-version
          git push -u origin HEAD