name: Automatic releasing after merge to main

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test
        run: npm run test

      - name: Build & Lint
        run: npm run build

      - name: Check for a potential new release
        id: release_check
        run: |
          pull_request_title="${{ github.event.pull_request.title }}"
          new_release_regex='(\[MAJOR\]|\[MINOR\]|\[PATCH\])\ .+'
          
          if [[ $pull_request_title =~ $new_release_regex ]]; then
            echo "::set-output name=new_release::true"
          fi

      - name: Publish
        if: steps.release_check.outputs.new_release == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Release to Github
        if: steps.release_check.outputs.new_release == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.update_version.outputs.tagName }}
          token: ${{ secrets.GITHUB_TOKEN }}