name: Automatic tag and release

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure git
        run: |
          git config --global user.email "ci@journify.io"
          git config --global user.name "Journify CI bot"

      - name: Update version
        id: update_version
        run: |
          pull_request_title="${{ github.event.pull_request.title }}"
          echo "PR title: $pull_request_title"
          
          majorRegex='\[MAJOR\]\ .+'
          minorRegex='\[MINOR\]\ .+'
          patchRegex='\[PATCH\]\ .+'
          new_version="false"
          
          if [[ $pull_request_title =~ $majorRegex ]]; then
            echo "Major version match"
            npm run major-version
            new_version="true"
          elif [[ $pull_request_title =~ $minorRegex ]]; then
            echo "Minor version match"
            npm run minor-version
            new_version="true"
          elif [[ $pull_request_title =~ $patchRegex ]]; then
            echo "Patch version match"
            npm run patch-version
            new_version="true"
          fi
          if [[ $new_version == "true" ]]; then
            current_version=$(node -p "require('./package.json').version")
            tagName="v$current_version"
          
            git push -u origin HEAD
          
            git tag -a $tagName -m "New version $tagName"
            git push origin $tagName

            echo "::set-output name=publish::true"
          fi

      - name: Test
        run: npm run test

      - name: Build & Lint
        run: npm run build

      - name: Publish
        if: steps.update_version.outputs.publish == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Release to Github
        if: steps.update_version.outputs.publish == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.update_version.outputs.tagName }}
          token: ${{ secrets.GITHUB_TOKEN }}